services:
  - type: web
    name: jeopardy-tournament
    runtime: node
    plan: free
    buildCommand: npm install && npm run build && npm run prisma:generate -w server
    startCommand: npm run prisma:migrate -w server && node server/dist/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: HOST_PASSCODE
        sync: false
      - key: TOKEN_SECRET
        generateValue: true
      - key: DATABASE_URL
        sync: false
      - key: PORT
        value: 10000
